"""create ia_responses table

Revision ID: 1ecdccdeedaa
Revises: c8130eefce1e
Create Date: 2025-10-01 11:57:46.701099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecdccdeedaa'
down_revision: Union[str, Sequence[str], None] = 'c8130eefce1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ia_responses', sa.Column('document_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ia_responses', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ia_responses', type_='foreignkey')
    op.drop_column('ia_responses', 'document_id')
    # ### end Alembic commands ###
